---
- name: Install java
  include_tasks: install_java.yaml

- name: Install jenkins
  include_tasks: install_jenkins.yaml

- name: Changing port number for jenkins
  template:
    src: jenkins.j2
    dest: /etc/default/jenkins
    owner: root
    group: root
  notify: restart jenkins
