- name: Copying tomcat 
  copy:
    src: apache-tomcat-8.5.57.tar.gz
    dest: /opt
  
- name: unzip tomcat
  shell: /bin/tar zxvf /opt/apache-tomcat-8.5.57.tar.gz -C /opt
    
- name: Deploy a War file
  copy:
    src: sample.war
    dest: /opt/apache-tomcat-8.5.57/webapps

- name: Starting the tomcat
  shell: nohup /opt/apache-tomcat-8.5.57/bin/startup.sh &
